### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by saravanan2611** [jathu1994/resume-to-job-matcher-Spacy-#1]
feed.txt is missing in your repository

**Comment by jatharthan** [comment]
actually the sections after "xxxxx" are just to simply check the model and view the results using **displacy** tools. nothing to do with the project. 
feed.txt is a simple file containing lots of technical skills to check how many skills are detected from paragraphs. you also can copy paste a para containing skills and check.
i have used jupyter notebook where i can run each sections independently. so i didn't remove these kind of test sections also from the file.
